### ISSUE TITLE
Move Plugin Site Label display names to the update center

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/plugin-site-api#82]
Currently label display names are stored locally as the Plugin Site API resource: https://github.com/jenkins-infra/plugin-site-api/blob/master/src/main/resources/labels.json . It does not make much sense, and it prevents other consumers from using them.

I suggest moving the display names to https://github.com/jenkins-infra/update-center2 directly

CC @jenkins-infra/plugin-site

**Comment by halkeye** [comment]
heck yes!

Just make it output a new file that can be cached/consumed? 

I don't think changing the main json to return strings is a good plan.

**Comment by daniel-beck** [comment]
Disagree strongly.

This proposal would bloat update center JSON, downloaded hundreds of thousands of times every day, for very little benefit except during short periods of increased labeling activity, like we're in now. Nobody should be using a Jenkins release with label/category definitions older than 4 months (and that's just LTS due to baseline age), so there's few user-friendly label names people would be missing out on.

**Comment by halkeye** [comment]
I don't think it needs to be in the json, just owned by update center. labels.json or something. I'm a big fan of static files that can be CDN'd over api servers that can go down

**Comment by daniel-beck** [comment]
@halkeye That makes sense, but isn't @oleg-nenashev's goal per https://github.com/jenkinsci/jenkins/pull/4534#issuecomment-593064783.

**Comment by oleg-nenashev** [comment]
Actually I would prefer a separate file as @halkeye says. The tricky part is serving it to Jenkins instances with custom update center. Maybe a build-time update is good enough

**Comment by daniel-beck** [comment]
> The tricky part is serving it to Jenkins instances with custom update center.

IOW,

> bloat update center JSON

would still apply.

**Comment by halkeye** [comment]
Coming back to this one, what about the labels being in jenkins core then, and we render the label name from core, else the tag. That isn't something that updates very often if ever really...

**Comment by zbynek** [comment]
Since https://github.com/jenkins-infra/plugin-site/pull/754 the label translations come from Core and label categories from `plugin-site`.
