### ISSUE TITLE
Plugin site cannot handle documentation URL of git plugin

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/plugin-site-api#83]
https://plugins.jenkins.io/git/

>  Documentation for this plugin is here: https://github.com/jenkinsci/git-plugin/tree/git-4.2.0/README.adoc 

https://github.com/jenkinsci/git-plugin/blob/c959c5d0c13e35899eb843fcea4f2e27dd52ea28/pom.xml#L25

Unclear whether this is supposed to work or not.

CC @MarkEWaite

**Comment by MarkEWaite** [comment]
Thanks for the report.  That attempt to use a maven-esque reference has failed.  I'll switch to simple and keep it simple.

**Comment by MarkEWaite** [comment]
Fixed in current master branch.  Fix will not be visible on plugins.jenkins.io until the next release of the git plugin

**Comment by MarkEWaite** [comment]
Same problem in the git client plugin, same fix, with same result, next release will fix the problem.

**Comment by halkeye** [comment]
btw this should get moved upstream to update-site, since we just consume the data from there.
