### ISSUE TITLE
Add code style to build

### ISSUE THREAD

**Issue by timja** [jenkins-infra/plugin-site-api#90]
Enforce code style by build
Bonus points if the tool automatically fixes issues

Ones I know of:

* Checkstyle
* fmt-maven-plugin
* google-java-format
* prettier-java / prettier-maven-plugin

Also see https://github.com/google/google-java-format#third-party-integrations

Not too worried about the code style as long as its sane and automated, ideally it matches closely to intellij defaults which are pretty good. If it's automated then doesn't matter much as the tool will just do it.

**Comment by timja** [comment]
This seems pretty good: https://github.com/jenkinsci/theme-manager-plugin/blob/master/.github/workflows/formatter.yml

**Comment by ameyanator** [comment]
Can I work on this?

**Comment by timja** [comment]
Sure I recommend `spotless-maven-plugin` with the google java format.

We're using it on a few Jenkins plugins now and it works nicely

https://github.com/jenkinsci/pipeline-graph-view-plugin/commit/6c9690ca442a3f0481943442c79a46eaad7fe29c

**Comment by zbynek** [comment]
Probably not worth doing for this repo (90% of the code here is unused).
